name: Trigger Actuator Refresh

on:
  push:
    branches:
      - main

jobs:
  refresh:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger actuator refresh
        run: |
          try {
            Write-Host "Triggering /actuator/refresh..."
            Invoke-RestMethod -Uri "http://localhost:8081/actuator/refresh" -Method 'POST' -Headers @{ "Accept" = "application/json" }
            Write-Host "Successfully triggered /actuator/refresh."
          } catch {
            Write-Host "Failed to trigger /actuator/refresh: $_"
            exit 1
          }
        shell: pwsh
