name: Trigger Actuator Refresh

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the action on

jobs:
  refresh:
    runs-on: windows-latest  # Since you're using PowerShell

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger actuator refresh
        run: |
          Invoke-RestMethod -Uri "http://localhost:8081/actuator/refresh" -Method 'POST' -Headers @{ "Accept" = "application/json" }
        shell: pwsh
